var commonNouns = {
  "one": "uno",
  "two": "dos",
  "three": "tres",
  "in": "en",
  "with": "con",
  "without": "sin",
  "to": "a",
  "in": "en",
  "during": "durante",
  "between": "entre",
  "yesterday": "ayer",
  "tomorrow": "mañana",
  "now": "ahora",
  "always": "siempre",
  "how": "cómo",
  "which": "cuál",
  "where": "dónde",
  "what": "qué",
  "when": "cuándo",
  "why": "por qué",
  "who": "quién",
  "but": "pero",
  "and": "y",
  "because": "porque",
  "yes": "sí",
  "she": "ella",
  "people": "pueblo",
  "peace": "la paz",
  "art": "el arte",
  "freedom": "la libertad",
  "nature": "la naturaleza",
  "religion": "la religión",
  "fashion": "la moda",
  "coffee": "el café",
  "wine": "el vino",
  "breakfast": "el desayuno",
};

var wordIndexes = {
  1: "one",
  2: "two",
  3: "three",
  4: "in",
  5: "with",
  6: "without",
  7: "to",
  8: "in",
  9: "during",
  10: "between",
  11: "yesterday",
  12:"tomorrow",
  13: "now",
  14: "always",
  15: "how",
  16: "which",
  17: "where",
  18: "what",
  19: "when",
  20: "why",
  21: "who",
  22: "but",
  23: "and",
  24: "because",
  25: "yes",
  26: "she",
  27: "people",
  28: "peace",
  29: "art",
  30: "freedom",
  31: "nature",
  32: "religion",
  33: "fashion",
  34: "coffee",
  35: "wine",
  36: "breakfast",
};
