var commonNouns = {
  "one": "uno",
  "two": "dos",
  "three": "tres",
  "in": "en",
  "with": "con",
  "without": "sin",
  "to have": "haber",
  "to do": "hacer",
  "to make": "hacer",
  "to go": "ir",
  "to see": "ver",
  "to give": "dar",
  "to believe": "creer",
  "to speak": "hablar",
  "to live": "vivir",
  "to work": "trabajar",
  "to understand": "entender",
  "to run": "correr",
  "in": "en",
  "during": "durante",
  "between": "entre",
  "yesterday": "ayer",
  "tomorrow": "mañana",
  "now": "ahora",
  "always": "siempre",
  "how": "cómo",
  "which": "cuál",
  "where": "dónde",
  "what": "qué",
  "when": "cuándo",
  "why": "por qué",
  "who": "quién",
  "but": "pero",
  "and": "y",
  "because": "porque",
  "yes": "sí",
  "she": "ella",
  "people": "pueblo",
  "peace": "la paz",
  "art": "el arte",
  "freedom": "la libertad",
  "nature": "la naturaleza",
  "religion": "la religión",
  "fashion": "la moda",
  "coffee": "el café",
  "wine": "el vino",
  "breakfast": "el desayuno",
};

var wordIndexes = {
  1: "one",
  2: "two",
  3: "three",
  4: "in",
  5: "with",
  6: "without",
  7: "to have",
  8: "to do",
  9: "to make",
  10: "to go",
  11: "to see",
  12: "to give",
  13: "to believe",
  14: "to speak",
  15: "to live",
  16: "to work",
  17: "to understand",
  18: "to run",
  19: "in",
  20: "during",
  21: "between",
  22: "yesterday",
  23:"tomorrow",
  24: "now",
  25: "always",
  26: "how",
  27: "which",
  28: "where",
  29: "what",
  30: "when",
  31: "why",
  32: "who",
  33: "but",
  34: "and",
  35: "because",
  36: "yes",
  37: "she",
  38: "people",
  39: "peace",
  40: "art",
  41: "freedom",
  42: "nature",
  43: "religion",
  44: "fashion",
  45: "coffee",
  46: "wine",
  47: "breakfast",
};
