var commonNouns = {
  "one": "uno",
  "two": "dos",
  "three": "tres",
  "in": "en",
  "with": "con",
  "without": "sin",
  "to": "a",
  "in": "en",
  "during": "durante",
  "between": "entre",
  "yesterday": "ayer",
  "tomorrow": "mañana",
  "now": "ahora",
  "always": "siempre",
  "how": "cómo",
  "which": "cuál",
  "where": "dónde",
  "what": "qué",
  "when": "cuándo",
  "why": "por qué",
  "who": "quién",
  "but": "pero",
  "and": "y",
  "because": "porque",
  "yes": "sí",
  "she": "ella",
  "people": "pueblo",
  "peace": "la paz",
  "art": "el arte",
  "freedom": "la libertad",
  "nature": "la naturaleza",
  "religion": "la religión",
  "fashion": "la moda",
  "coffee": "el café",
  "wine": "el vino",
  "breakfast": "el desayuno",
};
